/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package justfeed.GUI;

import Logica.*;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author UGent
 */
public class BestellingOverzicht extends javax.swing.JFrame {
    
    public Klant actief = LoginKlant.getInstance().getActief();
    public Order orderZonderKorting = Bestelling.getInstance().getOrderZonderKorting();
    public ArrayList<Menu> berekendeMenus = Bestelling.getInstance().getBerekendeMenus();
    java.sql.Date leveringsdatum = Bestelling.getInstance().getLeveringsdatum();
    ArrayList<Orderverwerking> besteldeProducten = Bestelling.getInstance().getBesteldeProducten();
    private static final BestellingOverzicht bestellingOverzicht = new BestellingOverzicht();
    public DefaultTableModel model = Bestelling.getInstance().getModel();
    public static JFrame myCaller;

    /**
     * Creates new form Overzichtbestelling
     */
    public BestellingOverzicht() {
        initComponents();
        double bedragexcl=0.0;
        for(Orderverwerking o:besteldeProducten){
            bedragexcl+=o.getPrijs()*o.getHoeveelheid();
        }
        double leveringskosten=orderZonderKorting.getTotaalPrijs()-bedragexcl;
        String leveringskosten1=String.valueOf(leveringskosten);
        String bedragexcl1=String.valueOf(bedragexcl);
        String totaalprijs2 = String.valueOf(orderZonderKorting.getTotaalPrijs());
        txtTotaalbedragexcl.setText(bedragexcl1);
        txtLeveringskosten.setText(leveringskosten1);
        txtTotaalbedrag.setText(totaalprijs2);
        tblOverzichtBestelling.setModel(model);
        txtTotaalbedrag.setEnabled(false);
        txtTotaalbedragexcl.setEnabled(false);
        txtLeveringskosten.setEnabled(false);
    }
    
    public static BestellingOverzicht getInstance(Bestelling caller)
    {
        myCaller = caller;
        return bestellingOverzicht;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAfleveradresToevoegen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOverzichtBestelling = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtTotaalbedrag = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTotaalbedragexcl = new javax.swing.JTextField();
        txtLeveringskosten = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Overzicht van uw bestelling");

        btnAfleveradresToevoegen.setBackground(new java.awt.Color(0, 0, 0));
        btnAfleveradresToevoegen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAfleveradresToevoegen.setForeground(new java.awt.Color(255, 255, 255));
        btnAfleveradresToevoegen.setText("Afleveradres toevoegen");
        btnAfleveradresToevoegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfleveradresToevoegenActionPerformed(evt);
            }
        });

        tblOverzichtBestelling.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblOverzichtBestelling);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Leveringskosten");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Totaalbedrag:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Totaalbedrag (excl. leveringskosten) :");

        txtTotaalbedragexcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotaalbedragexclActionPerformed(evt);
            }
        });

        txtLeveringskosten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLeveringskostenActionPerformed(evt);
            }
        });

        jLabel5.setText("----------------------------------------------------------------------------------------------------------------------------------------------------------------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(btnAfleveradresToevoegen, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTotaalbedragexcl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtLeveringskosten, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTotaalbedrag, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTotaalbedragexcl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLeveringskosten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotaalbedrag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addComponent(btnAfleveradresToevoegen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAfleveradresToevoegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfleveradresToevoegenActionPerformed
       BestellingAfleveradres adres = BestellingAfleveradres.getInstance(bestellingOverzicht);
       adres.pack();
       bestellingOverzicht.hide();
       adres.show();
       adres.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnAfleveradresToevoegenActionPerformed

    private void txtLeveringskostenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLeveringskostenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLeveringskostenActionPerformed

    private void txtTotaalbedragexclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotaalbedragexclActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotaalbedragexclActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BestellingOverzicht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BestellingOverzicht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BestellingOverzicht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BestellingOverzicht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BestellingOverzicht().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfleveradresToevoegen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOverzichtBestelling;
    private javax.swing.JTextField txtLeveringskosten;
    private javax.swing.JTextField txtTotaalbedrag;
    private javax.swing.JTextField txtTotaalbedragexcl;
    // End of variables declaration//GEN-END:variables
}
