/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package justfeed.GUI;

import Database.*;
import Logica.*;
import java.awt.Color;
import java.awt.Transparency;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author liedcost
 */
public class RapportStandVanZaken extends javax.swing.JFrame {

    private static final RapportStandVanZaken rapportSVZ = new RapportStandVanZaken();
    public Database d = new Database();
    public static JFrame myCaller;
    DefaultComboBoxModel c = d.initialiseerCombobox("SELECT naam FROM tbl_takeaway;", "naam");

    /**
     * Creates new form RapportStandVanZaken //
     */
    public RapportStandVanZaken() {
        initComponents();
        comboboxTakeAway.setModel(c);
    }

    public static RapportStandVanZaken getInstance(Administrator admini) {
        myCaller = admini;
        return rapportSVZ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        comboboxInhoud = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboboxTakeAway = new javax.swing.JComboBox();
        lblVestiging = new javax.swing.JLabel();
        lblTakeAway = new javax.swing.JLabel();
        btnRapportMaken = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        rbtnTakeAway = new javax.swing.JRadioButton();
        rbtnVestiging = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVestigingen = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Rapport met stand van zaken opvragen");

        comboboxInhoud.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Verkopen", "Lopende orders", "Lopende unieke actie kortingscodes" }));

        jLabel2.setText("Inhoud rapport");

        lblVestiging.setText("Selecteer de gewenste vestiging:");

        lblTakeAway.setText("Kies de betreffende take-away:");

        btnRapportMaken.setText("Rapport maken");
        btnRapportMaken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRapportMakenActionPerformed(evt);
            }
        });

        jLabel6.setText("Genereer rapport:");

        buttonGroup1.add(rbtnTakeAway);
        rbtnTakeAway.setText("per take-away");
        rbtnTakeAway.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnTakeAwayMouseClicked(evt);
            }
        });

        buttonGroup1.add(rbtnVestiging);
        rbtnVestiging.setText("per vestiging");
        rbtnVestiging.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnVestigingMouseClicked(evt);
            }
        });

        tblVestigingen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblVestigingen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtnTakeAway)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnVestiging))
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(lblVestiging)
                            .addComponent(jLabel2)
                            .addComponent(lblTakeAway))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboboxInhoud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboboxTakeAway, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnRapportMaken, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTakeAway)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnTakeAway)
                    .addComponent(rbtnVestiging))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVestiging, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(comboboxInhoud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboboxTakeAway, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRapportMaken)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnTakeAwayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnTakeAwayMouseClicked
            //comboboxVestiging.setEnabled(false);
            //lblVestiging.setForeground(Color.LIGHT_GRAY);
            DefaultTableModel model = (DefaultTableModel)tblVestigingen.getModel();
            model.setRowCount(0);
    }//GEN-LAST:event_rbtnTakeAwayMouseClicked

    private void rbtnVestigingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnVestigingMouseClicked
            //query om de vestigingen van de geselecteerde take-away op te halen
            //DefaultComboBoxModel f = d.initialiseerCombobox("SELECT vestigingsID FROM tbl_vestigingen;", "vestigingsID");
            String gekozenTakeAway;
            gekozenTakeAway = comboboxTakeAway.getSelectedItem().toString();
            //System.out.println(gekozenTakeAway);
            DefaultTableModel t = d.naarTabel("SELECT vestigingsID FROM tbl_vestigingen WHERE naam = '" + gekozenTakeAway + "';");
            tblVestigingen.setModel(t);
    }//GEN-LAST:event_rbtnVestigingMouseClicked

    private void btnRapportMakenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRapportMakenActionPerformed
        String gekozenTakeAway = comboboxTakeAway.getSelectedItem().toString();
        if(rbtnVestiging.isSelected()){
            int gekozenVestiging = tblVestigingen.getSelectedRow();
            String vestigingsID = tblVestigingen.getValueAt(gekozenVestiging,0).toString();
            Vestiging geselecteerdeVestiging = d.getVestiging(gekozenTakeAway,vestigingsID);
        }
        else if (rbtnTakeAway.isSelected()){
            Take_Away geselecteerdeTakeAway = d.getTakeaway(gekozenTakeAway);
        }
                
        else{}
        String inhoud = comboboxInhoud.getSelectedItem().toString();
        if(inhoud.equals("Verkopen")){
            
        }
        else if(inhoud.equals("Lopende orders")){
            
        }
        else{
            
        }
    }//GEN-LAST:event_btnRapportMakenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RapportStandVanZaken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RapportStandVanZaken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RapportStandVanZaken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RapportStandVanZaken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RapportStandVanZaken().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRapportMaken;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox comboboxInhoud;
    private javax.swing.JComboBox comboboxTakeAway;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTakeAway;
    private javax.swing.JLabel lblVestiging;
    private javax.swing.JRadioButton rbtnTakeAway;
    private javax.swing.JRadioButton rbtnVestiging;
    private javax.swing.JTable tblVestigingen;
    // End of variables declaration//GEN-END:variables
}
